### ISSUE TITLE
BUG - Semantic Search - Machine Learning = AI/ML

### ISSUE THREAD

**Issue by ErickRamirezAU** [PlanetCassandra/website#10]
When typing in a keyword, the result just shows a "Loading" and never completes. 

Added functionality: 

Search does not extend to Use Cases.

**Comment by allisonnokes** [comment]
@xingh @StefanVinica Are there any updates from Algolia for this?

**Comment by allisonnokes** [comment]
from @xingh Update on Semantic searching ability:

- Quick and maybe not so elegant fix for this is to use synonyms which can be done in Algolia dashboard

https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/how-to/managing-synonyms-from-the-dashboard/ 

Algolia Documentation
[Manage synonyms in the dashboard | Algolia](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/how-to/managing-synonyms-from-the-dashboard/)
Learn how to manage synonyms in the Algolia dashboard

To do this we would import a library of synonyms .. [https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/how-to/managing-synonyms-from-the-dashboard/#impo[…]file](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/how-to/managing-synonyms-from-the-dashboard/#import-synonyms-from-a-file)

Algolia Documentation
[Manage synonyms in the dashboard | Algolia](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/how-to/managing-synonyms-from-the-dashboard/#import-synonyms-from-a-file)

Learn how to manage synonyms in the Algolia dashboard
(https://anantco.slack.com/archives/C04TA4G74A1/p1684267273570959)

The alternative is to move away from Algolia to a tool like TypeSense which uses the instantsearch.js lib.
[Typesense](https://typesense.org/)
Lightning-fast, open source search engine for everyone (66 kB)
https://typesense.org/

for this we would first index, then and embed vectors with open AI embedding api -- https://github.com/typesense/typesense-instantsearch-semantic-search-demo
typesense/typesense-instantsearch-semantic-search-demo

this doesnt use openai but another open source library to do the embeddings - which is a great start --- the embeddings api from OPEN ai would make it better - embeddings are very very cheap compared to text completion
A demo that shows how to build a semantic search experience with Typesense's vector search feature and Instantsearch.js
[GitHub](https://anantco.slack.com/services/B01V2HFQFNH)

**Comment by StefanVinica** [comment]
This is Live
