### ISSUE TITLE
IMPROVEMENT - Remove Type field from Use Case submission form

### ISSUE THREAD

**Issue by ErickRamirezAU** [PlanetCassandra/website#11]
It doesn't make sense to me that a contributor has to explicity select `Case` in the mandatory `Type` field. As it clearly shows on the form, the field is "for internal use" only:

<img width="166" alt="use_case-type" src="https://github.com/PlanetCassandra/.github/assets/7269283/d5718546-06ff-491b-8cf7-c90de0f5f288">

I suspect this was a leftover from a previous design when a form could be used to submit different types of content. The field should be hidden from contributors and shouldn't appear in the form. Cheers!

**Comment by xingh** [comment]
@ErickRamirezAU I've made the default type for Submissions `Case` but it is not hidden by default if someone is sent to the form directly. 

I looked into having it hidden but still getting a value using the `prefilled_` and `hide_` options and I got it to  work well. 
hid it. 

https://airtable.com/shrYlu3mjtCiBTlOG?prefill_Type=Case&hide_Type=true

**Next Actions**

- [ ] update any static content links to this use case form the link above
- [ ] use the same type of solution for Link and Post submissions 

**References**
https://support.airtable.com/docs/prefilling-a-form#hiding-a-prefilled-field-from-the-submitter%E2%80%99s-view

**Comment by allisonnokes** [comment]
@andrejhristovski We need to update the links for the use case form to this link, please: https://airtable.com/shrYlu3mjtCiBTlOG?prefill_Type=Case&hide_Type=true

**Comment by allisonnokes** [comment]
@andrejhristovski Please update the Contribute a Link - url to : 

https://airtable.com/shr3vL0c2LrB4cwZ6?prefill_Type=Link&hide_Type=true

**Comment by allisonnokes** [comment]
@andrejhristovski Please update the contribute blog post idea to this link: 

https://airtable.com/shrEifAn99ub2Ny6g?prefill_Type=Post&hide_Type=true

**Comment by allisonnokes** [comment]
done. QA'd
