### ISSUE TITLE
BUG: 2 or more Use Cases for Same Company Name

### ISSUE THREAD

**Issue by allisonnokes** [PlanetCassandra/website#24]
When a different use case is submitted for the same company, a duplicate "card" is created on website.  

Scenario:

Week 1: User submits a use case for Company ABC - for Time Series Function.  Website publishes.
Week 2: User submits a different use case for the same Company ABC - but for a Data Store function.

When website publishes in Week 2, a duplicate card is created which renders the content from the Week 1 use case.  There are now two "cards" for that company (this is fine) - but the content for both cards is the same (wrong).

The url is the same for both cards. https://planetcassandra.org/usecases/bouygues-telecom/

![Image](https://user-images.githubusercontent.com/91761539/237841539-7dcdabba-aac9-4eea-adec-2f0e31229fa8.png)
![Image](https://user-images.githubusercontent.com/91761539/237841538-40a50a68-b6c6-41d6-8968-a801493ab2d7.png)
![Image](https://user-images.githubusercontent.com/91761539/237841540-4f02e0f1-4bbc-4511-b5c8-9a4570627953.png)
![Image](https://user-images.githubusercontent.com/91761539/237841537-0c55e040-af9c-4b43-bc27-8901554ba70c.png)

**Comment by StefanVinica** [comment]
This has been resolved lets do some QA and close it out if its good to go

**Comment by StefanVinica** [comment]
@ErickRamirezAU We might want to think about the case names a bit it would be beneficial to add context to the names rather than using the company names for the Case_Name it will increase SEO since we are using the title as meta tags
