### ISSUE TITLE
SEARCH Improvement: Facets

### ISSUE THREAD

**Issue by allisonnokes** [PlanetCassandra/website#26]
- User is able to utilize Facets on the left navigation to limit search results for any type of content - even the "All" types of content. 

- Facets should only show the top 7 tags, categories, items; with a "show more" link for the rest.  See Amazon screenshot for examples attached.

<img width="522" alt="Screenshot 2023-05-11 at 8 01 32 PM" src="https://github.com/PlanetCassandra/website/assets/91761539/f8097b24-923f-4d6b-9b03-67f69f27c846">
<img width="514" alt="Screenshot 2023-05-11 at 8 02 47 PM" src="https://github.com/PlanetCassandra/website/assets/91761539/a31d3070-4f02-479b-9264-e6c734adc956">

**Comment by allisonnokes** [comment]
Currently, "Show More" is on all facet groups - even if less than 7 things. Andrej has already fixed this in dev - will push to prod today.

**Comment by StefanVinica** [comment]
This is Fixed and is live
