### ISSUE TITLE
On Use Cases Main Page: Users should be able to filter by company, industry and use case function

### ISSUE THREAD

**Issue by allisonnokes** [PlanetCassandra/website#38]
From @pmcfadin 

On Use Cases Main Page: Users should be able to filter by company, industry and use case function

https://planetcassandra.org/usecases/

**Comment by StefanVinica** [comment]
This is in progress, we will take this into consideration when we create the mock

**Comment by allisonnokes** [comment]
Tijana has created mockups for Use Cases page on Wednesday. We will share in meeting today for feedback.

**Comment by allisonnokes** [comment]
fixed - on dev - will push to prod upon approval.
