### ISSUE TITLE
BUG - Continue Reading button displays over the image/title

### ISSUE THREAD

**Issue by ErickRamirezAU** [PlanetCassandra/website#4]
Button: Continue Reading - is over the image.  This doesn't happen with the other images

![Image](https://user-images.githubusercontent.com/91761539/232826384-2cac1e4f-8479-45f5-896f-a905b581c7bf.png)

**Comment by ErickRamirezAU** [comment]
This issue is due to us not using a standard image size. I propose we switch to 1024x512 for all featured images so they display consistently across the site.

Note that 1024x512 is the same dimensions we use for social posts so using it as the standard in Wordpress means that we don't have to create assets in multiple formats.

**Comment by StefanVinica** [comment]
This is resolved
