### ISSUE TITLE
Events Homepage Section

### ISSUE THREAD

**Issue by allisonnokes** [PlanetCassandra/website#44]
This task is dependent on getting the Events Data coming in from the Events PlugIn after we can re-implement the code

- Upcoming Events

**Comment by allisonnokes** [comment]
@StefanVinica Can you comment on the status of this? Should it be closed at this time?

**Comment by pmcfadin** [comment]
One of the reasons we went with the current plug-in was to have a map of all meetup groups. I want to make sure we keep that in mind during the redesign.

**Comment by StefanVinica** [comment]
We are keeping this in mind and we have been able to extract the events data from the plugin, its a bit not consistent but i will work on it to get it to the homepage

**Comment by allisonnokes** [comment]
Moving this offline.
