### ISSUE TITLE
Use Case Automation: Logo Auto-upload

### ISSUE THREAD

**Issue by ErickRamirezAU** [PlanetCassandra/website#5]

**Comment by allisonnokes** [comment]
1.  Progress: Stefan did a couple of tests on Monday (5/8) that were unsuccessful.
2.  Next Action: I will research and attempt to implement using Make to pull logo from Airtable and put in Github. I will ask Rahul for collaboration if necessary.

**Comment by StefanVinica** [comment]
There is progress on this issue, I was able to source and cache the images from Airtable on build time. @ErickRamirezAU @allisonnokes

**Comment by StefanVinica** [comment]
I've pushed the changes to Dev @allisonnokes if you can test it out on /usecases page to see if when you add an image for some of them that don't have on dev you can test it out

**Comment by allisonnokes** [comment]
This is operational.
