### ISSUE TITLE
Logate use case showing garbled Functional Use Cases

### ISSUE THREAD

**Issue by aar0np** [PlanetCassandra/website#58]
Kind of strange, but the new use case for Logate came through with the Functional Use Case list garbled.

https://planetcassandra.org/usecases/logate/358/

I checked Intuit (the other that I submitted today) and that one came through ok.

In looking at the `Submissions_All` table, and they look correct there (Session Store, Data Store).

**Comment by xingh** [comment]
1. Edited the .Cases table to reflect what was submitted in .Submissions. Fix has been made in Airtable. 
2. Found that new submissions were mapping the Functions data properly (there's a toggle) but the revised one's weren't. Fix has been made in Make.
3. Next build will update the content. 

![image](https://github.com/PlanetCassandra/website/assets/400761/731ff8f4-82f4-4860-85c4-73a5547a1e3c)

**Comment by xingh** [comment]
![image](https://github.com/PlanetCassandra/website/assets/400761/e6ea95e5-ac06-412a-a4f0-b102c35041de)

@aar0np looks like this is in prod now.

**Comment by aar0np** [comment]
NICE!  Thank you, Rahul!
