### ISSUE TITLE
BUG - Use case published date is set to submission date

### ISSUE THREAD

**Issue by ErickRamirezAU** [PlanetCassandra/website#59]
It looks like the use cases are out-of-order again because the `Case_Published` date in Airtable appears to be set to the submission date, not when the case was approved/published.

Here are examples:

```
Org                       | Submitted | Approved | Case_Published
--------------------------|-----------|----------|---------------
FamilySearch              | May 18    | May 24   | May 18
Intercontinental Exchange | May 19    | May 24   | May 19
```

**Comment by allisonnokes** [comment]
@ErickRamirezAU We are checking into this and it should be fixed soon.

**Comment by allisonnokes** [comment]
Bug identified, Fix is started.  Will update here when complete.

**Comment by allisonnokes** [comment]
Fixed in Dev.  This will be pushed tonight/tomorrow with other bug fixes.
