### ISSUE TITLE
REQUEST - Setup redirects for /tshirt, /contribute to planetcassandra.org/contact

### ISSUE THREAD

**Issue by ErickRamirezAU** [PlanetCassandra/website#61]
I'd like to propose setting up new URIs for marketing purposes. I think `planetcassandra.org/contact` is a bit awkward (personal opinion 🙂) when trying to solicit contributions from the community.

**Comment by ramseur** [comment]
This was released to production last week.  Request to close it @ErickRamirezAU

**Comment by ErickRamirezDS** [comment]
`/contribute` is working but https://planetcassandra.org/tshirt returns a 404 error.

**Comment by ramseur** [comment]
This is now resolved.  Lets close this ticket :) @ErickRamirezDS

**Comment by ErickRamirezAU** [comment]
Agreed, closed. Thanks! 🍻
