### ISSUE TITLE
Home page has trademark issues

### ISSUE THREAD

**Issue by pmcfadin** [PlanetCassandra/website#62]
This text block: 

Cassandra has a robust and active community of users and developers, who contribute to its development and use it in a variety of applications, ranging from e-commerce to real-time analytics.

Should read:
Apache Cassandra® has a robust and active community of users and developers, who contribute to its development and use it in a variety of applications, ranging from e-commerce to real-time analytics.

**Comment by ramseur** [comment]
Acknowledged.  Will update when this is complete.

**Comment by ramseur** [comment]
This is live on production @pmcfadin .  Request to close

**Comment by michaelsembwever** [comment]
The reported Trademark issue is fixed, thanks! 

But… 
we're had a report upstream like i'd like to forward to here as it's related:

```
Welcome to Planet.Cassandra

Apache Cassandra® a robust and active community of users and developers …
```

This is confusing the Planet Cassandra and Apache Cassandra communities.  The previous paragraph was much better in how it stated the Planet Cassandra was a community supporting (/surrounding) the upstream community.  It is important that this distinction is always present.

From Mark
> This would be a perfect place to clearly distinguish between the two and provide prominent links back to [cassandra.apache.org](http://cassandra.apache.org/)

**Comment by michaelsembwever** [comment]
@ramseur @pmcfadin we need to prioritise this, 3 weeks has passed (i promised an update on progress after 2 weeks).

**Comment by michaelsembwever** [comment]
@StefanVinica @allisonnokes

**Comment by StefanVinica** [comment]
@michaelsembwever I will take care of it

**Comment by StefanVinica** [comment]
![image](https://github.com/PlanetCassandra/website/assets/26149819/2b608b04-8880-4de3-84a1-224eb2dd0fd1)

**Comment by michaelsembwever** [comment]
This is still ambiguous about what community planetcassandra is.  It needs to state what its community is, not describe the upstream community.

**Comment by StefanVinica** [comment]
Just write what it should say i will add it to the site

**Comment by michaelsembwever** [comment]
What was previously there was perfect.  Do we still have a copy of that ?

**Comment by StefanVinica** [comment]
this?
Apache Cassandra® a robust and active community of users and developers,
          who contribute to its development and use it in a variety of
          applications, ranging from e-commerce to real-time analytics

**Comment by michaelsembwever** [comment]
before that

**Comment by StefanVinica** [comment]
ok i found these 2 in the commits
1. Welcome to Planet Cassandra. A place for the Apache Cassandra® user community to share with each other.
2. Cassandra has a robust and active community of users and developers, who contribute to its development and use it in a variety of applications, ranging from e-commerce to real-time analytics.

**Comment by michaelsembwever** [comment]
it was (1) that i was referring to.  thanks. 

feel free to choose or combine between (1) and that in my previous comment.

**Comment by StefanVinica** [comment]
awesome i pushed this, give me a few hours for USA people to come online so i can deploy it to prod.

**Comment by StefanVinica** [comment]
https://planetcassandra.org/
