### ISSUE TITLE
Make "Apache Cassandra" nav link a little more prominent

### ISSUE THREAD

**Issue by michaelsembwever** [PlanetCassandra/website#64]
A request has come from in ASF (with thanks that this link now exists) if it can be made a little more prominent. 

I have no opinion, but I can image using the Cassandra log (hyperlinked) instead of the text could be one possible approach.

**Comment by michaelsembwever** [comment]
@ramseur @pmcfadin @StefanVinica @allisonnokes  we need to prioritise this, 3 weeks has passed (i promised an update on progress after 2 weeks).

**Comment by StefanVinica** [comment]
@michaelsembwever I will look into it

**Comment by michaelsembwever** [comment]
the third or the fourth.  (with the logo, with or without the border)

thanks !!

**Comment by StefanVinica** [comment]
https://planetcassandra.org/
