### ISSUE TITLE
Document somewhere the intent and distinction of Planet Cassandra (in comparison to cassandra.a.o)

### ISSUE THREAD

**Issue by michaelsembwever** [PlanetCassandra/website#65]
Request came in

> It would be incredibly useful if this intention was documented somewhere. That would allow both review of the overall intention and review of content against that intention which I think could significantly reduce the number and frequency of concerns being raised.

I'll come up with some draft text of this intent, and I hope we can find the right place to put it.

**Comment by michaelsembwever** [comment]
My first draft: 
---

As community around the Apache Cassandra project, Planet Cassandra aims to compliment the wider ecosystem.

Planet Cassandra is a place where content from vendors or that promoting a vendor can be submitted.  Planet Cassandra also acts as an aggregator of existing external web content.  

This makes it a facilitator to the broader ecosystem, and a place where commercial actors can be active where they otherwise cannot be within the project.  Formally, within the ASF projects only individual contributors are recognised to ensure a vendor-neutral and sustainable open source project, see The Apache Way for more on this.

Everything official and formal to the Cassandra project is found on cassandra.apache.org. This includes all documentation, technical blog posts (especially those from our committers), and information about approved events.

The Apache Cassandra project recognises that success of the project is bound to the commercial success of entities in its ecosystem, and in line with the ASF's commercially friendly but vendor-neutral ethos, embraces Planet Cassandra in this mission.

**Comment by michaelsembwever** [comment]
FYI @ramseur @pmcfadin @StefanVinica @allisonnokes

**Comment by StefanVinica** [comment]
@michaelsembwever we will get this done asap

**Comment by StefanVinica** [comment]
we added this on the contribute page
<img width="866" alt="image" src="https://github.com/PlanetCassandra/website/assets/26149819/045bf9b8-9c18-4313-9f16-262f545629ee">

**Comment by michaelsembwever** [comment]
perfect. thanks @StefanVinica !

**Comment by StefanVinica** [comment]
Ill push it to Prod by EOD
