### ISSUE TITLE
Remove AstraDB and Datastax filter buttons

### ISSUE THREAD

**Issue by michaelsembwever** [PlanetCassandra/website#66]
![Screenshot 2023-12-18 at 22 55 36](https://github.com/PlanetCassandra/website/assets/559444/dee205a3-7509-489d-b406-e8ffdd62c5f3)

On the home page, these filter buttons exist.

Both the AstraDB and Datastax buttons are not appropriate, being vendor specific.  (The alternative is to permit all vendors, but I struggle to see how design-wise this would be practical.)

Please remove both buttons.  Suggestions for alternatives are "Analytics", "Time Series", "Personalization"

**Comment by michaelsembwever** [comment]
@xingh

**Comment by rbowen** [comment]
Just to put in a strenuous +1 - this is not a "nice to have", but is required to maintain the vendor-neutral stance that PlanetCassandra advertises. Please consider this a request from the Board. Thanks.

**Comment by StefanVinica** [comment]
those 2 tags have been removed, will update Prod.

**Comment by StefanVinica** [comment]
@rbowen @michaelsembwever we have removed the tags, close the issue when review

**Comment by michaelsembwever** [comment]
thank you @StefanVinica
